#!/usr/bin/env python

import logging
logging.basicConfig(level=logging.DEBUG)

import os

import vanilla


class Connected(object):
    def __init__(self, hub):
        self.hub = hub
        self.connected = []

    def broadcast(self):
        for ch in self.connected:
            ch.send(len(self.connected))

    def subscribe(self):
        ch = self.hub.channel()
        self.connected.append(ch)
        self.broadcast()
        return ch

    def unsubscribe(self, ch):
        self.connected.remove(ch)
        self.broadcast()


print 'start'
h = vanilla.Hub()
app = h.http.cup(
    host='0.0.0.0',
    port=8000,
    base_path=os.path.join(os.path.dirname(__file__)))

app.static('/', 'index.html')

connected = Connected(h)


@app.websocket('/')
def index(ws):
    watch = connected.subscribe()

    @h.spawn
    def _():
        try:
            while True:
                ws.recv()
        except vanilla.Closed:
            watch.close()

    for count in watch:
        try:
            ws.send(str(count))
        except vanilla.Closed:
            break

    connected.unsubscribe(watch)

h.stop_on_term()
print 'peace.'
