#!/usr/bin/env python

import logging
logging.basicConfig(level=logging.DEBUG)

import json
import os

import vanilla


print 'start'

h = vanilla.Hub()

app = h.http.cup(
    host='0.0.0.0',
    port=8000,
    base_path=os.path.join(os.path.dirname(__file__)))

app.static('/', 'index.html')


@app.websocket('/')
def index(ws):
    while True:
        try:
            ch, data = h.select(ws)
        except vanilla.Closed:
            break


h.stop_on_term()
print 'peace.'
