#!/usr/bin/env python

import logging
import sys
import os

import vanilla


def main():
    logging.basicConfig(level=logging.DEBUG)

    print 'starting...'
    h = vanilla.Hub()

    app = h.http.bean(
        host='0.0.0.0',
        port=8000,
        base_path=os.path.join(os.path.dirname(__file__)))

    app.static('/', 'index.html')

    @app.post('/')
    def _(request, response):
        print "----"
        print request.consume()
        return 'OK'

    h.stop_on_term()
    print 'shutdown.'


if __name__ == '__main__':
    sys.exit(main())
